-- VetSpace domain schema: taxonomy, users, content, sessions, access, extras.
-- UUID PKs (generated by the application; DEFAULT gen_random_uuid() is a
-- safety net for rows inserted outside Hibernate). Enums are stored as
-- VARCHAR + CHECK so the allowed values are enforced and self-documenting
-- in psql, matching @Enumerated(EnumType.STRING) on the Java side.

-- =====================================================================
-- Taxonomy & users
-- =====================================================================

CREATE TABLE schools (
    id   uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    name varchar(255) NOT NULL,
    slug varchar(255) NOT NULL,
    CONSTRAINT ux_schools_slug UNIQUE (slug)
);

CREATE TABLE users (
    id               uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    email            varchar(255) NOT NULL,
    username         varchar(50) NOT NULL,
    password_hash    varchar(255) NOT NULL,
    last_name        varchar(100) NOT NULL,
    first_name       varchar(100) NOT NULL,
    role             varchar(20) NOT NULL CHECK (role IN ('ADMIN', 'TEACHER', 'STUDENT')),
    status           varchar(20) NOT NULL CHECK (status IN ('ACTIVE', 'DISABLED')),
    -- Nullable: school/study_year are unset until the student redeems a
    -- pack (or for ADMIN/TEACHER accounts that aren't tied to one school).
    school_id        uuid NULL,
    study_year       int NULL,
    photo_url        varchar(500) NULL,
    theme_primary    varchar(20) NULL,
    theme_secondary  varchar(20) NULL,
    theme_tertiary   varchar(20) NULL,
    created_at       timestamptz NOT NULL DEFAULT now(),
    updated_at       timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT ux_users_username UNIQUE (username),
    -- School deletion must not delete accounts; it only clears the
    -- affiliation, since a user's identity/history outlives the school row.
    CONSTRAINT fk_users_school FOREIGN KEY (school_id) REFERENCES schools (id) ON DELETE SET NULL
);

-- Case-insensitive uniqueness on email regardless of how the app stores it.
CREATE UNIQUE INDEX ux_users_email_lower ON users (lower(email));
CREATE INDEX idx_users_school_id ON users (school_id);

CREATE TABLE refresh_tokens (
    id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id    uuid NOT NULL,
    token_hash varchar(255) NOT NULL,
    expires_at timestamptz NOT NULL,
    revoked_at timestamptz NULL,
    CONSTRAINT ux_refresh_tokens_token_hash UNIQUE (token_hash),
    -- A token is meaningless without its user; deleting the account (e.g.
    -- GDPR erasure) must not leave orphaned credential rows behind.
    CONSTRAINT fk_refresh_tokens_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX idx_refresh_tokens_user_id ON refresh_tokens (user_id);

CREATE TABLE password_reset_tokens (
    id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id    uuid NOT NULL,
    token_hash varchar(255) NOT NULL,
    expires_at timestamptz NOT NULL,
    used_at    timestamptz NULL,
    CONSTRAINT ux_password_reset_tokens_token_hash UNIQUE (token_hash),
    -- Same reasoning as refresh_tokens: cascades with the owning account.
    CONSTRAINT fk_password_reset_tokens_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX idx_password_reset_tokens_user_id ON password_reset_tokens (user_id);

-- =====================================================================
-- Content
-- =====================================================================

CREATE TABLE modules (
    id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    school_id  uuid NOT NULL,
    study_year int NOT NULL,
    name       varchar(255) NOT NULL,
    position   int NOT NULL,
    published  boolean NOT NULL DEFAULT false,
    -- Modules are strictly owned by a school; there is no independent use
    -- for a module once its school is gone, so the whole content subtree
    -- cascades from here down to propositions/mindmaps.
    CONSTRAINT fk_modules_school FOREIGN KEY (school_id) REFERENCES schools (id) ON DELETE CASCADE
);

CREATE INDEX idx_modules_school_id ON modules (school_id);

CREATE TABLE courses (
    id        uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    module_id uuid NOT NULL,
    name      varchar(255) NOT NULL,
    position  int NOT NULL,
    published boolean NOT NULL DEFAULT false,
    -- A course cannot exist without its module.
    CONSTRAINT fk_courses_module FOREIGN KEY (module_id) REFERENCES modules (id) ON DELETE CASCADE
);

CREATE INDEX idx_courses_module_id ON courses (module_id);

CREATE TABLE source_exams (
    id        uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    school_id uuid NOT NULL,
    label     varchar(255) NOT NULL,
    year      int NOT NULL,
    exam_type varchar(20) NOT NULL CHECK (exam_type IN ('ENTRAINEMENT', 'EXAMEN')),
    -- Exam metadata is school-owned catalog data, same lifecycle as modules.
    CONSTRAINT fk_source_exams_school FOREIGN KEY (school_id) REFERENCES schools (id) ON DELETE CASCADE
);

CREATE INDEX idx_source_exams_school_id ON source_exams (school_id);

CREATE TABLE questions (
    id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    course_id         uuid NOT NULL,
    statement         text NOT NULL,
    statement_images  jsonb NOT NULL DEFAULT '[]'::jsonb,
    source_exam_id    uuid NULL,
    difficulty        varchar(10) NULL CHECK (difficulty IN ('EASY', 'MEDIUM', 'HARD')),
    published         boolean NOT NULL DEFAULT false,
    created_at        timestamptz NOT NULL DEFAULT now(),
    updated_at        timestamptz NOT NULL DEFAULT now(),
    -- A question cannot exist without its course.
    CONSTRAINT fk_questions_course FOREIGN KEY (course_id) REFERENCES courses (id) ON DELETE CASCADE,
    -- Losing exam provenance shouldn't destroy the question; just clear it.
    CONSTRAINT fk_questions_source_exam FOREIGN KEY (source_exam_id) REFERENCES source_exams (id) ON DELETE SET NULL
);

CREATE INDEX idx_questions_course_id ON questions (course_id);
CREATE INDEX idx_questions_source_exam_id ON questions (source_exam_id);

CREATE TABLE propositions (
    id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    question_id         uuid NOT NULL,
    letter              varchar(1) NOT NULL CHECK (letter IN ('A', 'B', 'C', 'D', 'E')),
    text                text NOT NULL,
    is_true             boolean NOT NULL,
    explanation_html    text NULL,
    explanation_images  jsonb NOT NULL DEFAULT '[]'::jsonb,
    position            int NOT NULL,
    -- A proposition has no meaning outside its question.
    CONSTRAINT fk_propositions_question FOREIGN KEY (question_id) REFERENCES questions (id) ON DELETE CASCADE
);

CREATE INDEX idx_propositions_question_id ON propositions (question_id);

CREATE TABLE mindmaps (
    id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    course_id  uuid NOT NULL,
    title      varchar(255) NOT NULL,
    image_url  varchar(500) NOT NULL,
    published  boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    -- A mindmap has no meaning outside its course.
    CONSTRAINT fk_mindmaps_course FOREIGN KEY (course_id) REFERENCES courses (id) ON DELETE CASCADE
);

CREATE INDEX idx_mindmaps_course_id ON mindmaps (course_id);

-- =====================================================================
-- Sessions & answers
-- =====================================================================

CREATE TABLE sessions (
    id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id        uuid NOT NULL,
    title          varchar(255) NOT NULL,
    session_type   varchar(20) NOT NULL CHECK (session_type IN ('ENTRAINEMENT', 'EXAMEN')),
    -- Snapshot of the filters used to build the session (module/courses/
    -- sources/etc.), kept so "repeat with same filters" can replay it.
    filters        jsonb NOT NULL DEFAULT '{}'::jsonb,
    question_count int NOT NULL,
    favorite       boolean NOT NULL DEFAULT false,
    rating         int NULL CHECK (rating BETWEEN 1 AND 5),
    status         varchar(20) NOT NULL CHECK (status IN ('ACTIVE', 'SUBMITTED')),
    started_at     timestamptz NOT NULL DEFAULT now(),
    submitted_at   timestamptz NULL,
    total_seconds  int NOT NULL DEFAULT 0,
    score          numeric(5, 2) NULL,
    -- A session is personal study history; it's deleted with the account.
    CONSTRAINT fk_sessions_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX idx_sessions_user_id ON sessions (user_id);

CREATE TABLE session_questions (
    session_id   uuid NOT NULL,
    question_id  uuid NOT NULL,
    position     int NOT NULL,
    state        varchar(20) NOT NULL DEFAULT 'UNANSWERED' CHECK (state IN ('UNANSWERED', 'ANSWERED', 'CONSULTED')),
    is_correct   boolean NULL,
    seconds_spent int NOT NULL DEFAULT 0,
    PRIMARY KEY (session_id, question_id),
    -- Row is meaningless without its session; cascades transitively from
    -- sessions.user_id as well.
    CONSTRAINT fk_session_questions_session FOREIGN KEY (session_id) REFERENCES sessions (id) ON DELETE CASCADE,
    -- Questions that have been used in any session carry historical answer
    -- data (scores, past attempts); block hard-deleting a question that
    -- has been studied. Admins retire content via questions.published=false
    -- instead of deleting it.
    CONSTRAINT fk_session_questions_question FOREIGN KEY (question_id) REFERENCES questions (id) ON DELETE RESTRICT
);

CREATE INDEX idx_session_questions_question_id ON session_questions (question_id);

CREATE TABLE session_answers (
    id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    session_id    uuid NOT NULL,
    question_id   uuid NOT NULL,
    proposition_id uuid NOT NULL,
    selected      boolean NOT NULL,
    -- One row per selected proposition, scoped to a specific
    -- session_questions row (composite FK), which itself cascades from
    -- sessions -> nothing extra to do here but follow the same lifecycle.
    CONSTRAINT fk_session_answers_session_question FOREIGN KEY (session_id, question_id)
        REFERENCES session_questions (session_id, question_id) ON DELETE CASCADE,
    -- Defense in depth: propositions with recorded answers are already
    -- protected transitively (their question can't be deleted while
    -- session_questions references it), but RESTRICT here makes the
    -- protection explicit at the answer layer too.
    CONSTRAINT fk_session_answers_proposition FOREIGN KEY (proposition_id) REFERENCES propositions (id) ON DELETE RESTRICT
);

CREATE INDEX idx_session_answers_session_question ON session_answers (session_id, question_id);
CREATE INDEX idx_session_answers_proposition_id ON session_answers (proposition_id);

-- =====================================================================
-- Access
-- =====================================================================

CREATE TABLE packs (
    id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    school_id     uuid NOT NULL,
    -- NULL study_year = a résidanat-style pack that isn't scoped to a
    -- single year.
    study_year    int NULL,
    name          varchar(255) NOT NULL,
    academic_year varchar(20) NOT NULL,
    price_da      int NOT NULL,
    active        boolean NOT NULL DEFAULT true,
    expires_at    timestamptz NOT NULL,
    -- Packs are part of a school's catalog; removing the school removes
    -- the packs it sold (subscriptions still guard against orphaning paid
    -- access, see below).
    CONSTRAINT fk_packs_school FOREIGN KEY (school_id) REFERENCES schools (id) ON DELETE CASCADE
);

CREATE INDEX idx_packs_school_id ON packs (school_id);

CREATE TABLE activation_codes (
    id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    pack_id    uuid NOT NULL,
    code_hash  varchar(255) NOT NULL,
    max_uses   int NOT NULL DEFAULT 1,
    used_count int NOT NULL DEFAULT 0,
    revoked    boolean NOT NULL DEFAULT false,
    -- Nullable: keep the code (and its redemption history) even if the
    -- admin who generated it is later removed; only the attribution is lost.
    created_by uuid NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT ux_activation_codes_code_hash UNIQUE (code_hash),
    -- Codes belong to exactly one pack and are worthless without it.
    CONSTRAINT fk_activation_codes_pack FOREIGN KEY (pack_id) REFERENCES packs (id) ON DELETE CASCADE,
    CONSTRAINT fk_activation_codes_created_by FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE SET NULL
);

CREATE INDEX idx_activation_codes_pack_id ON activation_codes (pack_id);
CREATE INDEX idx_activation_codes_created_by ON activation_codes (created_by);

CREATE TABLE subscriptions (
    id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id             uuid NOT NULL,
    pack_id             uuid NOT NULL,
    activation_code_id  uuid NOT NULL,
    starts_at           timestamptz NOT NULL,
    ends_at             timestamptz NOT NULL,
    -- A subscription is personal entitlement data; it goes with the account.
    CONSTRAINT fk_subscriptions_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    -- Block deleting a pack that granted real entitlements; force admins to
    -- deactivate it (packs.active=false) instead of silently revoking paid
    -- access via a hard delete.
    CONSTRAINT fk_subscriptions_pack FOREIGN KEY (pack_id) REFERENCES packs (id) ON DELETE RESTRICT,
    -- Codes are revoked, not deleted (see activation_codes.revoked), so this
    -- should never fire in practice; RESTRICT protects the redemption audit
    -- trail if a code row is ever removed directly.
    CONSTRAINT fk_subscriptions_activation_code FOREIGN KEY (activation_code_id) REFERENCES activation_codes (id) ON DELETE RESTRICT
);

CREATE INDEX idx_subscriptions_user_id ON subscriptions (user_id);
CREATE INDEX idx_subscriptions_pack_id ON subscriptions (pack_id);
CREATE INDEX idx_subscriptions_activation_code_id ON subscriptions (activation_code_id);

-- =====================================================================
-- Extras
-- =====================================================================

CREATE TABLE labels (
    id      uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id uuid NOT NULL,
    name    varchar(100) NOT NULL,
    color   varchar(20) NOT NULL,
    -- Personal taxonomy; removed with the account.
    CONSTRAINT fk_labels_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX idx_labels_user_id ON labels (user_id);

CREATE TABLE question_labels (
    label_id    uuid NOT NULL,
    question_id uuid NOT NULL,
    PRIMARY KEY (label_id, question_id),
    -- Join row is meaningless without either side.
    CONSTRAINT fk_question_labels_label FOREIGN KEY (label_id) REFERENCES labels (id) ON DELETE CASCADE,
    CONSTRAINT fk_question_labels_question FOREIGN KEY (question_id) REFERENCES questions (id) ON DELETE CASCADE
);

CREATE INDEX idx_question_labels_question_id ON question_labels (question_id);

CREATE TABLE notes (
    id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id      uuid NOT NULL,
    -- Both nullable and independent: a note can stand alone, be pinned to
    -- a question, or be pinned to a course.
    question_id  uuid NULL,
    course_id    uuid NULL,
    title        varchar(255) NOT NULL,
    content_html text NOT NULL,
    created_at   timestamptz NOT NULL DEFAULT now(),
    updated_at   timestamptz NOT NULL DEFAULT now(),
    -- Personal content; removed with the account.
    CONSTRAINT fk_notes_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    -- Detach rather than destroy: the note's own title/content still stand
    -- on their own if the linked question or course disappears.
    CONSTRAINT fk_notes_question FOREIGN KEY (question_id) REFERENCES questions (id) ON DELETE SET NULL,
    CONSTRAINT fk_notes_course FOREIGN KEY (course_id) REFERENCES courses (id) ON DELETE SET NULL
);

CREATE INDEX idx_notes_user_id ON notes (user_id);
CREATE INDEX idx_notes_question_id ON notes (question_id);
CREATE INDEX idx_notes_course_id ON notes (course_id);

CREATE TABLE signals (
    id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id     uuid NOT NULL,
    question_id uuid NOT NULL,
    message     text NOT NULL,
    status      varchar(20) NOT NULL DEFAULT 'OPEN' CHECK (status IN ('OPEN', 'RESOLVED', 'REJECTED')),
    admin_reply text NULL,
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now(),
    -- A report is tied to the reporting account; removed together.
    CONSTRAINT fk_signals_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    -- A report about a question is meaningless once the question is gone.
    CONSTRAINT fk_signals_question FOREIGN KEY (question_id) REFERENCES questions (id) ON DELETE CASCADE
);

CREATE INDEX idx_signals_user_id ON signals (user_id);
CREATE INDEX idx_signals_question_id ON signals (question_id);

CREATE TABLE notifications (
    id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    title      varchar(255) NOT NULL,
    body       text NOT NULL,
    kind       varchar(20) NOT NULL CHECK (kind IN ('UPDATE', 'QUESTIONS', 'INFO')),
    -- Nullable targeting: NULL school/study_year means broadcast to everyone.
    school_id  uuid NULL,
    study_year int NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    -- Keep the notification content if its target school is removed; only
    -- the targeting metadata becomes meaningless, not the announcement itself.
    CONSTRAINT fk_notifications_school FOREIGN KEY (school_id) REFERENCES schools (id) ON DELETE SET NULL
);

CREATE INDEX idx_notifications_school_id ON notifications (school_id);

CREATE TABLE notification_reads (
    user_id         uuid NOT NULL,
    notification_id uuid NOT NULL,
    read_at         timestamptz NOT NULL DEFAULT now(),
    deleted         boolean NOT NULL DEFAULT false,
    PRIMARY KEY (user_id, notification_id),
    -- Personal read-state; removed with the account.
    CONSTRAINT fk_notification_reads_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    -- Read marker is meaningless without the notification it refers to.
    CONSTRAINT fk_notification_reads_notification FOREIGN KEY (notification_id) REFERENCES notifications (id) ON DELETE CASCADE
);

CREATE INDEX idx_notification_reads_notification_id ON notification_reads (notification_id);

CREATE TABLE support_messages (
    id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id    uuid NOT NULL,
    subject    varchar(255) NOT NULL,
    body       text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    -- Personal support history; removed with the account (no separate
    -- retention requirement has been specified).
    CONSTRAINT fk_support_messages_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX idx_support_messages_user_id ON support_messages (user_id);
